version: '3.1'

services:

  db:
    image: postgres
    container_name: db_user
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  server:
    image: golang:1.20-alpine3.18
    container_name: login_server
    restart: always
    working_dir: /app
    ports:
      - 80:80
      - 443:443   
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      DB_URL: postgres://db:5432