version: '3.1'

services:

  db:
    image: postgres:13
    container_name: db_user
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      ENVIRONMENT: ${ENVIRONMENT}

  server:
    image: golang:1.20.4-alpine3.18
    container_name: login_server
    command: tail -F /dev/null
    restart: always
    working_dir: /app
    ports:
      - 80:80
      - 443:443   
    environment:
      DB_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      ENVIRONMENT: ${ENVIRONMENT}